name: Deploy Automatico

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Atualizar Servidor Oracle via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORACLE_USER }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            # Acessa a pasta exata onde o bot está no servidor
            cd ~/shopee
            
            # Sincroniza o código com o GitHub forçando a cópia exata
            git fetch --all
            git reset --hard origin/main
            
            # Atualiza as bibliotecas se houver mudanças
            source venv/bin/activate
            pip install -r requirements.txt --no-cache-dir
            
            # Recarrega as configurações do sistema caso algum .service tenha sido alterado no GitHub
            sudo systemctl daemon-reload
            
            EXIBIR_LOGS="true"
            
            # 1. Reinicia o Bot Mestre (Antigo Shopee)
            if [ "$EXIBIR_LOGS" = "true" ]; then echo "🚀 Reiniciando Bot Mestre..."; fi
            sudo systemctl stop bot_mestre_bot.service || true
            sudo systemctl kill -s SIGKILL bot_mestre_bot.service || true
            sudo systemctl start bot_mestre_bot.service
            
            # 2. Reinicia o Userbot de Divulgacao
            if [ "$EXIBIR_LOGS" = "true" ]; then echo "🚀 Reiniciando Divulgação Canal..."; fi
            sudo systemctl stop divulgacao_canal_bot.service || true
            sudo systemctl kill -s SIGKILL divulgacao_canal_bot.service || true
            sudo systemctl start divulgacao_canal_bot.service

            # 3. Reinicia o Motor Userbot (Antigo Espião)
            if [ "$EXIBIR_LOGS" = "true" ]; then echo "🕵️ Reiniciando Motor Userbot..."; fi
            sudo systemctl stop motor_userbot_bot.service || true
            sudo systemctl kill -s SIGKILL motor_userbot_bot.service || true
            sudo systemctl start motor_userbot_bot.service

            # 4. Reinicia o Espelhador de Videos Autorais
            if [ "$EXIBIR_LOGS" = "true" ]; then echo "🔄 Reiniciando Espelhador Autorais..."; fi
            sudo systemctl stop espelhador_videos_autorais_bot.service || true
            sudo systemctl kill -s SIGKILL espelhador_videos_autorais_bot.service || true
            sudo systemctl start espelhador_videos_autorais_bot.service
            
            if [ "$EXIBIR_LOGS" = "true" ]; then echo "🚪 Encerrando a conexão SSH de forma limpa..."; fi
            exit 0
